ip: "127.0.0.1"
port_hello: 8082
port_count: 8081
port_query: 8083
api:
  max_message_size: 32
usecase:
  default_message: "hello, world"
  default_message_count: 0
  default_message_query: "Hello, sweeties <3"
db:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "sana2005A"
  dbname: "web-10"
